version: '3.9'
services:
  php-apache:
    image: php:8.1-apache
    container_name: apache-php
    build:
      dockerfile: 'Dockerfile'
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html
